// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Bruno Mollo",
            "url": "https://github.com/BrunoMollo"
        },
        "license": {
            "name": "MIT",
            "url": "TODO:add"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/start": {
            "post": {
                "description": "Responds with the slug to the newly started game.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Recives a word a start a game",
                "parameters": [
                    {
                        "description": "Secret Word",
                        "name": "word",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.RequestBody_CreateGame"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Game slug (identifier)",
                        "schema": {
                            "type": "Response_CreateGame"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.RequestBody_CreateGame": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "secret"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Hangman API",
	Description:      "An api to play the famous Hangman game of guessing words.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
