name: Go 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    name: Format Backend Code 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.20"
      - name: Run gofmt
        working-directory: ./backend
        run: gofmt -l .

  unit-test:
    name: Unit Tests in Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.20"
      - name: Install dependencies
        working-directory: ./backend
        run: go mod tidy
      - name: Run tests
        working-directory: ./backend/logic
        run: go test -coverprofile=cover.prof
      - name: Insatall report tool
        run: go install github.com/cancue/covreport@latest
      - name: Generate coverage report
        working-directory: ./backend/logic
        run: ~/go/bin/covreport
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[Github Action]-> Update Coverage Report'
          branch: ${{ github.head_ref }}

  check-build:
    name: Check that Backends Compiles 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.20"
      - name: Build project
        working-directory: ./backend
        run: go build -o output
